server:
  port: 8888
#基于SpringBoot 2.x版本，如果使用oracle驱动的话，请使用oracle 11+版本，oracle 10版本会出现兼容性问题
spring:
  datasource:
    url: jdbc:mysql://10.28.96.132:3306/activiti6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    #url: jdbc:oracle:thin:@(description=(address_list= (address=(host=10.0.8.173) (protocol=tcp)(port=1521))(address=(host=10.0.8.173)(protocol=tcp) (port=1521)) (load_balance=yes)(failover=yes))(connect_data=(service_name= devdb)))
    driver-class-name: com.mysql.jdbc.Driver #oracle.jdbc.driver.OracleDriver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
     initial-size: 5      #初始化连接个数
     max-active: 20       #最大连接个数
     min-idle: 5          #最小连接个数
     max-wait: 6000       #最大等待时间
     pool-prepared-statements: true                        #开启缓存PSCache
     max-pool-prepared-statement-per-connection-size: 20   #指定每个连接上PSCache的大小
     time-between-eviction-runs-millis: 6000               #在空闲连接回收器线程运行期间休眠的时间值
     min-evictable-idle-time-millis: 100000                # 配置一个连接在池中最小生存的时间
     validation-query: SELECT 1 FROM DUAL                  #用来检测连接是否有效的sql
     validation-query-timeout: 60000                       #检查sql超时时间
     test-while-idle: true     #申请连接的时候检测
     test-on-borrow: false     #申请连接时执行validationQuery检测连接是否有效
     test-on-return: false     #归还连接时执行validationQuery检测连接是否有效
     # 配置DruidStatFilter
     web-stat-filter:
       enabled: true
       url-pattern: "/*"
       exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,*.html"
     #开启监控页面
     stat-view-servlet:
       url-pattern: "/druid/*"
       enabled: true
       login-username: admin
       login-password: admin
       # IP白名单(没有配置或者为空，则允许所有访问)
       allow:
       # IP黑名单 (存在共同时，deny优先于allow)
       deny:
       #  禁用HTML页面上的“Reset All”功能
       reset-enable: false
     stat:
       enabled: true
       log-slow-sql: true
       slow-sql-millis: 1000
     #开启Slf4jFilter
     slf4j:
       enabled: true
       data-source-log-enabled: false
       connection-log-enabled: false
       statement-log-enabled: false
       result-set-log-enabled: false
     #开启WallFilter
     wall:
       enabled: true
       log-violation: true
       throw-exception: false
       config:
         delete-where-none-check: true
     #开启Web监控
     web-stat:
       enabled: true
     #开启Aop监控
     aop-stat:
       enabled: true
#activiti6配置项
  activiti:
    check-process-definitions: true #自动检查、部署流程定义文件
    database-schema-update: true #自动更新数据库结构
    #流程定义文件存放目录
    process-definition-location-prefix: classpath:/processes/
    #process-definition-location-suffixes: #流程文件格式
  redis:
    host: localhost
    port: 6379
    database: 0
#    password:
    timeout: 10000
  freemarker:
    # 禁用模板缓存
    cache: false
    # 编码格式
    charset: UTF-8
    # freemarker模板后缀 默认是 .ftl  .html
    suffix: .ftl
    # 是否为此技术启用MVC视图分辨率。
    enabled: true
    # Content-Type值
    content-type: text/html
    # #模板加载路径 按需配置 ,默认路径是 classpath:/templates/
    template-loader-path: classpath:/ftl/
    settings:
      number_format: "0.##"
